datastore/api/urls.py
from django.urls import path
from django.views.generic import TemplateView

from drf_spectacular.views import (
    SpectacularRedocView,
    SpectacularSwaggerView,
)

import api.control.api
import api.experimental.api
import api.grantnav.api
import api.dashboard.api
import api.org.api
import api.org.api_schema


app_name = "api"

urlpatterns = [
    path("", TemplateView.as_view(template_name="api.html"), name="index"),
    path(
        "dashboard/publishers",
        api.dashboard.api.Publishers.as_view(),
        name="publishers",
    ),
    path(
        "dashboard/overview",
        api.dashboard.api.Overview.as_view(),
        name="overview",
    ),
    path(
        "dashboard/publisher/<str:publisher_prefix>",
        api.dashboard.api.Publisher.as_view(),
        name="publisher",
    ),
    path(
        "grantnav/updates",
        api.grantnav.api.GrantNavPollForNewData.as_view(),
        name="grantnav-updates",
    ),
    path("control/status", api.control.api.StatusView.as_view(), name="status"),
    path(
        "control/trigger-datagetter",
        api.control.api.TriggerDataGetter.as_view(),
        name="trigger-datagetter",
    ),
    path(
        "control/abort-datagetter",
        api.control.api.AbortDataGetter.as_view(),
        name="abort-datagetter",
    ),
    path(
        "experimental/CurrentLatestGrants",
        api.experimental.api.CurrentLatestGrants.as_view(),
        name="current-latest-grants",
    ),
    # Public API
    path(
        "v1/org/<path:org_id>/grants_made/",
        api.org.api.OrganisationGrantsMadeView.as_view(),
        name="organisation-grants-made",
    ),
    path(
        "v1/org/<path:org_id>/grants_received/",
        api.org.api.OrganisationGrantsReceivedView.as_view(),
        name="organisation-grants-received",
    ),
    path(
        "v1/org/<path:org_id>/",
        api.org.api.OrganisationDetailView.as_view(),
        name="organisation-detail",
    ),
    path(
        "v1/org/",
        api.org.api.OrganisationListView.as_view(),
        name="organisation-list",
    ),
    # Schema UI
    path(
        "v1/schema/",
        api.org.api_schema.APISchemaView.as_view(),
        name="schema",
    ),
    # Optional UI:
    path(
        "v1/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="swagger-ui",
    ),
    path(
        "v1/redoc/",
        SpectacularRedocView.as_view(url_name="api:schema"),
        name="redoc",
    ),
]

datastore/ui/urls.py
from django.urls import path
from django.views.generic import TemplateView

import ui.views

app_name = "ui"

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("explore", TemplateView.as_view(template_name="explore.html"), name="explore"),
    path("explore/latest", ui.views.ExploreLatestView.as_view(), name="explore-latest"),
    path(
        "explore/datagetter",
        ui.views.ExploreDatagetterView.as_view(),
        name="explore-datagetter",
    ),
    path("dashboard", ui.views.DashBoardView.as_view(), name="dashboard"),
    path("dashboard/log/<slug:log_name>", ui.views.LogView.as_view(), name="log"),
]

datastore/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

# This is the root urlconf

urlpatterns = [
    path("", include("ui.urls", namespace="ui"), name="ui_index"),
    path("api/", include("api.urls", namespace="api"), name="api_index"),
    path(
        "prometheus/",
        include("prometheus.urls", namespace="prometheus"),
        name="prom_index",
    ),
    path("admin/", admin.site.urls, name="admin"),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

datastore/ui/views.py
import datetime
import os
import subprocess

from django.conf import settings
from django.db.models import Q
from django.views.generic import TemplateView

import db.models as db

# Note To require login use LoginRequiredMixin
# from django.contrib.auth.mixins import LoginRequiredMixin
# and set login_url = reverse_lazy("admin:login")
# from django.urls import reverse_lazy


class ExploreDatagetterView(TemplateView):
    template_name = "explore_datagetter.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["errors"] = []

        context["getter_runs"] = db.GetterRun.objects.order_by("-datetime")

        try:

            if (
                "getter_run" in self.request.GET
                and "-1" not in self.request.GET["getter_run"]
            ):
                getter_run = context["getter_runs"].get(
                    pk=self.request.GET["getter_run"]
                )

                context["getter_run_selected"] = getter_run

                if (
                    "publisher" in self.request.GET
                    and "-1" not in self.request.GET["publisher"]
                ):
                    publisher = getter_run.publisher_set.get(
                        prefix=self.request.GET["publisher"]
                    )

                    context["publisher_selected"] = publisher
        except (db.GetterRun.DoesNotExist, db.Publisher.DoesNotExist) as e:
            context["errors"].append(str(e))
            pass

        return context


class ExploreLatestView(TemplateView):
    template_name = "explore_latest.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        context["errors"] = []

        context["latests"] = db.Latest.objects.all()

        try:

            if "latest" in self.request.GET and "-1" not in self.request.GET["latest"]:
                context["latest_selected"] = context["latests"].get(
                    pk=self.request.GET["latest"]
                )

                if (
                    "source" in self.request.GET
                    and "-1" not in self.request.GET["source"]
                ):
                    context["source_selected"] = context[
                        "latest_selected"
                    ].sourcefile_set.get(pk=self.request.GET["source"])

        except (db.Latest.DoesNotExist, db.SourceFile.DoesNotExist) as e:
            context["errors"].append(str(e))
            pass

        return context


class DashBoardView(TemplateView):
    template_name = "dash.html"

    @staticmethod
    def git_revision():
        return subprocess.check_output(
            ["git show --format=format:%h  --no-patch"], shell=True
        ).decode()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["last_datagetter_run"] = db.GetterRun.objects.order_by(
            "-datetime"
        ).first()
        context["total_grants"] = db.Grant.estimated_total()
        context["total_datagetter_runs"] = db.GetterRun.objects.count()

        # May not be generated yet
        try:
            context["latest_current"] = db.Latest.objects.get(series=db.Latest.CURRENT)
        except db.Latest.DoesNotExist:
            pass

        # May not be generated yet
        try:
            context["latest_previous"] = db.Latest.objects.get(
                series=db.Latest.PREVIOUS
            )
        except db.Latest.DoesNotExist:
            pass

        # May not be generated yet
        try:
            context["problem_sources"] = context[
                "last_datagetter_run"
            ].sourcefile_set.filter(
                Q(data_valid=False) | Q(downloads=False) | Q(acceptable_license=False)
            )
        except AttributeError:
            pass

        # Not critical if this fails e.g. git not installed
        try:
            context["git_rev"] = DashBoardView.git_revision()
        except Exception:
            pass

        return context


class LogView(TemplateView):
    template_name = "log.html"

    def read_log_file(self, log_file):
        """Returns log content and datetime of modified"""
        try:
            with open(log_file, "r") as f:
                return (
                    f.read(),
                    datetime.datetime.fromtimestamp(int(os.stat(log_file).st_mtime)),
                )

        except FileNotFoundError:
            return "Error unable to read log file", ""

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        log_name = kwargs.get("log_name")

        context["log_content"] = "No valid log selected"

        if not log_name:
            return context

        if log_name == "data_run":
            log_file = getattr(settings, "DATA_RUN_LOG", "")

            context["log_content"], context["date_modified"] = self.read_log_file(
                log_file
            )

        return context

datastore/ui/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script
      src="https://code.jquery.com/jquery-3.6.3.min.js"
      integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- /Bootstrap 4 -->

    <script>
      /* little script to show menu active states */
      $(document).ready(function(){
        $(".nav-link").each(function(){
          if (window.location.href == $(this).prop('href')){
            $(this).addClass("active");
          } else {
            $(this).removeClass("active");
          }
        });
      })
    </script>
  {% load prettyjson %}
  {% prettyjson_setup jquery='False' %}
  <title>{% block title %}{% endblock %} - 360 Giving Datastore</title>
  </head>
  <body class="d-flex flex-column h-100">
    <main role="main">
      <div class="container mt-2 mb-4 bg-dark">
          <nav class="navbar navbar-expand-sm navbar-dark rounded">
            <ul class="navbar-nav">
             <li class="nav-item">
                <a class="nav-link" href="{% url 'ui:index' %}">Home</a>
              </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'ui:dashboard' %}">Dashboard</a>
              </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'ui:explore' %}">Explore</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'api:index' %}">API</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Data Admin</a>
              </li>
            </ul>
          </nav>
       </div>
        {% block content %}{% endblock %}
    </main>
  </body>
</html>

datastore/ui/templates/dash.html
{% extends "base.html" %}

{% load humanize %}
{% load prettyjson %}

{% block title %}Dashboard{% endblock %}

{% block content %}

{% if errors %}
<div class="alert alert-warning">
  {% for error in errors %}
  <p>{{error}}</p>
  {% endfor %}
</div>
{% endif %}


<div class="container">

  <div class="row bg-light">
    <div class="col">

      <h1>Info</h1>
      <p>Datastore running at revision <a
          href="https://github.com/ThreeSixtyGiving/datastore/commit/{{git_rev}}">{{git_rev}}</a>.</p>
      <p>Total Grants in the system is approximately {{total_grants|intcomma}} from {{total_datagetter_runs}} Datagetter
        runs.</p>

    </div>
  </div>

  <div class="row bg-light">
    <div class="col">

      <table class="table table-hover">
        <thead>
          <th scope="col">Dataset</th>
          <th scope="col">Updated</th>
          <th scope="col">Grants</th>
          <th scope="col">Source Files</th>
          <th scope="col"></th>
        </thead>
        <tbody>
          <tr>
            <td>Current Latest</td>
            <td>{{latest_current.updated|date:"r"}}</td>
            <td>{{latest_current.grant_set.all.count|intcomma}}
              {% if latest_current.grant_set.all.count > latest_previous.grant_set.all.count %}
              <span class="text-success">&#9650;</span>
              {% elif latest_current.grant_set.all.count < latest_previous.grant_set.all.count %}
              <span class="text-danger">&#9660;</span>
              {% endif %}
            </td>
            <td>{{latest_current.sourcefile_set.all.count|intcomma}}</td>
            <td>
              {% if not latest_current %}
              No Latest data generated
              {% else %}
              <a href="{% url "ui:log" 'data_run' %}">Datarun log</a>,
              <a href="/reports">Data Reports</a>,
              <a href="{% url "ui:explore-latest" %}?latest={{latest_current.pk}}">Explore data</a>
              {% endif %}
            </td>
          </tr>

          <tr>
            <td>Previous Latest</td>
            <td>{{latest_previous.updated|date:"r"}}</td>
            <td>{{latest_previous.grant_set.all.count|intcomma}}</td>
            <td>{{latest_previous.sourcefile_set.all.count|intcomma}}</td>
            <td>
              {% if not latest_previous %}
              No Latest data generated
              {% else %}
              <a href="{% url "ui:explore-latest" %}?latest={{latest_previous.pk}}">Explore data</a>
              {% endif %}
            </td>
          </tr>

          <tr>
            <td>Datagetter</td>
            <td>{{last_datagetter_run.datetime|date:"r"}}</td>
            <td>{{last_datagetter_run.grant_set.all.count|intcomma}}</td>
            <td>{{last_datagetter_run.sourcefile_set.all.count|intcomma}}</td>
            <td>
              <a href="{% url "ui:explore-datagetter" %}?getter_run={{last_datagetter_run.id}}">Explore data</a>,
              <a href="/reports">Data Reports</a>
            </td>
          </tr>
        </tbody>
      </table>

    </div>
  </div>

</div>

<div class="container mt-3">
  <div class="row bg-light">
    <div class="col">

      <h2>Problem Sources Summary ({{problem_sources|length}})</h2>
      {% if problem_sources|length > 0 %}
      <p><a href="{% url "ui:log" 'data_run' %}">{{last_datagetter_run.datetime|date:"r"}}</a></p>
      <table class="table table-hover">
        <thead>
          <th scope="col">Source</th>
          <th scope="col">Issue(s)</th>
        </thead>
        <tbody>

      {% for problem_source in problem_sources %}
      <tr>
      <td><!-- db ID:{{problem_source.pk }} -->
        {{problem_source.data.publisher.prefix}} - {{problem_source.data.title}} {% for dist in problem_source.data.distribution %}<a class="d-block" href="{{dist.downloadURL}}">{{forloop.counter}} - Download URL</a> {% endfor %}
      </td>
      <td>
        {% if problem_source.downloads == False %}
          <span class="d-block text-break">Download failed {{problem_source.data.datagetter_metadata.error}}</span>
        {% else %}
          {% if problem_source.acceptable_license == False %}<span class="d-block">No acceptable license</span>{% endif %}
          {% if problem_source.data_valid == False %}<span class="d-block">Validation error</span>{% endif %}
        {% endif %}
      </td>
      </tr>

      {% endfor %}
      </tbody>
      </table>

      {% else %}
      <p>No problem sources!</p>

      {% endif %}

    </div>
  </div>
</div>


<div class="container mt-3 mb-3">
  <div class="row bg-light">
    <div class="col">

      <h2 class="d-inline-block">System Status</h2> <small>(updates every 5 seconds)</small>
      <pre id="checked-time"></pre>

      <div id="status-area" style="height: 100px; overflow: auto;" class="border mb-2 p-1 bg-white">
      </div>
      <button class="btn btn-sm btn-danger" id="run-datagetter-btn">Run Datagetter process</button>
      <button class="btn btn-sm btn-secondary" id="abort-datagetter-btn">Abort Datagetter process</button>

    </div>
  </div>
</div>

<script>
  var getterStatusUrl = "{% url "api:status" %}";
  var triggerDatagetterUrl = "{% url "api:trigger-datagetter" %}";
  var abortDatagetterUrl = "{% url "api:abort-datagetter" %}";
</script>

<script>
  var statusArea = $("#status-area");

  function updateStatus() {
    $("#checked-time").text(new Date().toTimeString());
    // Clear old statues
    statusArea.html("");

    $.getJSON(getterStatusUrl, function (status) {
      for (let items in status.statuses) {
        let whatEl = $("<pre class='d-inline mr-2'></pre>").text(status.statuses[items].what);
        let statusEl = $("<pre class='d-inline'></pre>").text(status.statuses[items].status);

        let container = $("<div></div>");
        container.append(whatEl);
        container.append(statusEl);

        statusArea.append(container);
      }
    }).fail(function(error){
      let errorEl = $("<pre></pre>").text(error.statusText);
      statusArea.append(errorEl);
    });
  }

  $(document).ready(function(){
    updateStatus();

    setInterval(updateStatus, 5000);

    $("#run-datagetter-btn").click(function(){
      $.getJSON(triggerDatagetterUrl, function(data){
        alert("Response: " + data.error + " Process ID: "+ data.pid);
        console.log(data);
      });
    });

    $("#abort-datagetter-btn").click(function () {
      if (confirm("Note depending on when in the process this aborts it may require manual intervention to restore a previous state")){
        $.getJSON(abortDatagetterUrl, function(data){
          console.log(data);
        });
      }
    });

  });
</script>
{% endblock %}

datastore/ui/templates/explore.html
{% extends "base.html" %}
{% block title %}Explore data{% endblock %}
{% block content %}
<div class="container">
    <h2>Explore the data</h2>
    <ul>
        <li><a href="{% url "ui:explore-datagetter" %}">Datagetter runs</a></li>
        <li><a href="{% url "ui:explore-latest" %}">Latest data</a></li>
    </ul>
</div>
{% endblock %}

datastore/ui/templates/explore_datagetter.html
{% extends "base.html" %}
{% load prettyjson %}

{% block title %}Explore data{% endblock %}

{% block content %}

<div class="container">
  <h2>Explore Datagetter runs</h2>
  {% if errors %}
  <div class="alert alert-warning">
    {% for error in errors %}
    <p>{{error}}</p>
    {% endfor %}
  </div>
  {% endif %}

  <form method="GET" id="object-selector-form">
    <div class="form-group">
      <label for="data-getter-select">Datagetter run</label>
      <select name="getter_run" id="data-getter-select" class="form-control">
        <option value="-1">--</option>

        {% for getter_run in getter_runs %}

        {% if getter_run_selected.pk == getter_run.pk %}
        <option value="{{getter_run.pk}}" selected>{{getter_run.datetime|date:"r"}}</option>
        {% else %}
        <option value="{{getter_run.pk}}">{{getter_run.datetime|date:"r"}}</option>
        {% endif %}

        {% endfor %}

      </select>
    </div>

    {% if getter_run_selected %}
    <div class="form-group">
      <label for="publisher-select">Publishers</label>
      <select name="publisher" id="publisher-select" class="form-control">
        <option value="-1">--</option>
        {% for publisher in getter_run_selected.publisher_set.all %}

        {% if publisher_selected.pk == publisher.pk %}
        <option value="{{publisher.prefix}}" selected>{{publisher.prefix}} - {{publisher.name}}</option>
        {% else %}
        <option value="{{publisher.prefix}}">{{publisher.prefix}} - {{publisher.name}}</option>
        {% endif %}

        {% endfor %}
      </select>
    </div>


    {% endif %}

  </form>
  <a class="text-muted" href="?">reset</a>
</div>

<div class="container">
  {% if publisher_selected  %}

  <div class="list-group d-none" id="grants-list">
    <div class="list-group-item">
      <h2>{{publisher_selected.name}} ({{publisher_selected.grant_set.count}} Grants) </h2>
    </div>

    <div class="list-group-item d-none" id="publisher-data">
      {% prettyjson publisher_selected.data initial="parsed" %}
    </div>

  {% for grant in publisher_selected.grant_set.all %}
    <div class="list-group-item">
      <h4>{{grant.grant_id}}</h4>
      {% prettyjson grant.data %}
      <div class="ml-4 mt-2">
        <h5>additional_data</h5>
        {% prettyjson grant.additional_data  initial="parsed" %}
      </div>
    </div>
  {% endfor %}

  </div>
  {% endif %}
</div>


<script>
  $(document).ready(function(){
    let form = $("#object-selector-form");

    $("select").change(function(){
      form.submit();
    });

    /* Hack to add bootstrap style to the jsonwidget templates */
    $(".jsonwidget").each(function(){
      $(this).children("textarea").addClass("form-control");
      $(this).find("button").addClass("btn btn-sm btn-secondary d-inline");
    });


    $("#grants-list").removeClass("d-none");
    $("#publisher-data").removeClass("d-none");
    /* end Hack */
  });
</script>
{% endblock %}

datastore/ui/templates/explore_latest.html
{% extends "base.html" %}
{% load prettyjson %}
{% load humanize %}

{% block title %}Explore Latest data{% endblock %}

{% block content %}

<div class="container">
  <h2>Explore Latest data</h2>
  {% if errors %}
  <div class="alert alert-warning">
    {% for error in errors %}
    <p>{{error}}</p>
    {% endfor %}
  </div>
  {% endif %}
  <form method="GET" id="object-selector-form">
    <div class="form-group">
      <label for="latest-select">Latest</label>
      <select name="latest" id="dataset-select" class="form-control">
        <option value="-1" >--</option>

        {% for latest in latests %}

        {% if latest_selected.pk == latest.pk %}
        <option value="{{latest.pk}}" selected>{{latest.series}} {{latest.updated|date:"r"}}</option>
        {% else %}
        <option value="{{latest.pk}}">{{latest.series}} {{latest.updated|date:"r"}}</option>
        {% endif %}

        {% endfor %}

      </select>
    </div>

    {% if latest_selected %}
    <div class="form-group">
      <label for="source-select">Sources</label>
      <select name="source" id="source-select" class="form-control">
        <option value="-1">--</option>
        {% for source in latest_selected.sourcefile_set.all %}

        {% if source_selected.pk == source.pk %}
        <option value="{{source.pk}}" selected>{{source.data.publisher.prefix}} - {{source.data.title}}</option>
        {% else %}
        <option value="{{source.pk}}">{{source.data.publisher.prefix}} - {{source.data.title}}</option>
        {% endif %}

        {% endfor %}
      </select>
    </div>


    {% endif %}

  </form>
  <a class="text-muted mb-2" href="?">reset</a>
</div>
<div class="container">
  {% if source_selected  %}

  <div class="list-group d-none" id="grants-list">
    <div class="list-group-item">
      <h2>{{source_selected.data.title}}</h2>
      <ul>
        <li>Grants: {{source_selected.grant_set.count|intcomma}} </li>
        <li>From Datagetter run: <a href="{% url 'ui:explore-datagetter' %}?getter_run={{source_selected.getter_run.pk}}&publisher={{source_selected.data.publisher.prefix}}">{{source_selected.getter_run.datetime|date:"r"}}</a> </li>
        <li>Identifier: {{source_selected.data.identifier}}</li>
      </ul>
    </div>

    <div class="list-group-item d-none" id="source-data">
      {% prettyjson source_selected.data initial="parsed" %}
    </div>

  {% for grant in source_selected.grant_set.all %}
    <div class="list-group-item">
      <h4>{{grant.grant_id}}</h4>
      {% prettyjson grant.data %}
      <div class="ml-4 mt-2">
        <h5>additional_data</h5>
        {% prettyjson grant.additional_data  initial="parsed" %}
      </div>
    </div>
  {% endfor %}

  </div>
  {% endif %}
</div>


<script>
  $(document).ready(function(){
    let form = $("#object-selector-form");

    $("select").change(function(){
      form.submit();
    });

    /* Hack to add bootstrap style to the jsonwidget templates */
    $(".jsonwidget").each(function(){
      $(this).children("textarea").addClass("form-control");
      $(this).find("button").addClass("btn btn-sm btn-secondary d-inline");
    });


    $("#grants-list").removeClass("d-none");
    $("#publisher-data").removeClass("d-none");
    /* end Hack */
  });
</script>
{% endblock %}

datastore/ui/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container">
    <p>The 360 Giving Datastore application.</p>
    <p>The Datastore stores data that has been fetched from the 360 giving registry via the datagetter tool. The datastore keeps 31 datasets from the 'datagetting' process in the database in order that queries can be performed on it. The datastore generates grantnav data packages in order to keep grantnav up to date.</p>
    <p><a href="https://github.com/ThreeSixtyGiving/datastore">Datastore project on github</a></p>
</div>
{% endblock %}

datastore/ui/templates/log.html
{% extends "base.html" %}
{% load prettyjson %}

{% block title %}Dev Explore data{% endblock %}

{% block content %}

{% load humanize %}
<div class="container d-flex justify-content-between">
  <h1>Log view </h1>
  <h4 class="align-self-end">{{view.kwargs.log_name}} {{date_modified|date:'r'}}</h4>
</div>

<div class="container bg-light">
  <pre class="p-3">{{log_content}}</pre>
</div>

{% endblock %}